import blurPlaceholders from "@/data/portfolio-blur.json";
import posterPaths from "@/data/portfolio-posters.json";
import portfolioAssets from "@/data/random-portfolio.json";
import { VIDEO_EXTENSION } from "@/lib/utils/video-extension";

/**
 * The carousel's media, derived from the UploadThing manifest at
 * `src/data/random-portfolio.json`.
 *
 * This is asset data, not copy, which is why it does not live in
 * `content/home.ts` alongside the page's text. The manifest is the export from
 * the bucket and is meant to be replaced wholesale when the bucket changes —
 * nothing here needs editing when it does. When it is replaced, also re-run
 * `bun run generate:blur` (`scripts/generate-portfolio-blur.ts`) so
 * `src/data/portfolio-blur.json` picks up blur placeholders for the new
 * images and prunes the ones that dropped out, and `bun run generate:posters`
 * (`scripts/generate-portfolio-posters.ts`) so the videos get a first-frame
 * poster in `public/portfolio-posters/`.
 *
 * The host is already whitelisted in `next.config.ts` (`ve7o52t8ra.ufs.sh`),
 * so the images go through the Next image optimizer. The videos do not — they
 * are served as-is. Their posters are local files, so those are optimized.
 */

type PortfolioMediaKind = "image" | "video";

export interface PortfolioMedia {
  /** The UploadThing key. Unique per file, and stable across re-exports. */
  id: string;
  kind: PortfolioMediaKind;
  url: string;
  /**
   * A 12px-wide WebP still, inlined, standing in until the real file paints.
   * Generated by `scripts/generate-portfolio-blur.ts`. Present for both
   * kinds: for images it is sampled straight from the file, for videos it
   * comes from a frame extracted roughly half a second in. Can still be
   * absent for a key the generator has not run for yet (a newly added
   * manifest entry, or a video placeholder skipped because ffmpeg was not
   * installed when the script last ran).
   */
  blurDataUrl?: string;
  /**
   * Videos only. The public path of a full-size still of the clip's first
   * frame, generated by `scripts/generate-portfolio-posters.ts`. The card
   * shows it exactly the way it shows an image, and the clip fades in over
   * it once it is actually playing — so a video that is still buffering
   * looks like an image, not like a blur. Absent for a video the generator
   * has not run for yet, in which case the card falls back to showing the
   * clip's own first decoded frame.
   */
  posterUrl?: string;
}

/**
 * The JSON imports type as object literals with exactly the keys present in
 * each file, valued as `string` — not as open-ended maps. Indexing them with
 * an arbitrary `asset.key` therefore needs a wider, explicit type; this is
 * that widening, kept local to the one place that needs it rather than
 * weakening the imports' types everywhere they are used.
 */
const blurDataUrlsByKey: Record<string, string> = blurPlaceholders;
const posterUrlsByKey: Record<string, string> = posterPaths;

/**
 * Kind is read off the filename because the manifest carries no MIME type.
 * Anything not matching is treated as an image, which is the safe default —
 * a mislabelled video renders as a broken image rather than as an element
 * that tries to autoplay.
 */
export const portfolioMedia: readonly PortfolioMedia[] = portfolioAssets.map(asset => {
  const kind: PortfolioMediaKind = VIDEO_EXTENSION.test(asset.name) ? "video" : "image";
  const blurDataUrl = blurDataUrlsByKey[asset.key];
  const posterUrl = kind === "video" ? posterUrlsByKey[asset.key] : undefined;

  return {
    id: asset.key,
    kind,
    url: asset.url,
    ...(blurDataUrl ? { blurDataUrl } : {}),
    ...(posterUrl ? { posterUrl } : {}),
  };
});
