/**
 * Compiles data/hyph_is.dic and data/exceptions.txt into src/generated/data.ts.
 *
 * Run from the repo root: bun run generate:skiptingar
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const PACKAGE_ROOT = join(import.meta.dir, "..");

export const DIC_PATH = join(PACKAGE_ROOT, "data", "hyph_is.dic");
export const EXCEPTIONS_PATH = join(PACKAGE_ROOT, "data", "exceptions.txt");
export const GENERATED_PATH = join(PACKAGE_ROOT, "src", "generated", "data.ts");

const PATTERN_LINE = /^[\p{L}\d.]+$/u;
const UNSAFE_IN_TEMPLATE = /[`\\$]/;
const NEWLINES = /\r?\n/;

/** Plain Liang pattern lines of a hunspell dictionary, header lines dropped. */
export function extractPatterns(dic: string): string[] {
  const patterns: string[] = [];
  for (const raw of dic.split(NEWLINES)) {
    const line = raw.trim();
    if (line === "" || line === "UTF-8" || /^[A-Z]+ /.test(line)) {
      continue;
    }
    if (!PATTERN_LINE.test(line)) {
      throw new Error(`hyph_is.dic: unsupported pattern line: ${line}`);
    }
    patterns.push(line);
  }
  return patterns;
}

function asTemplateLiteral(lines: string[]): string {
  const body = lines.join("\n");
  if (UNSAFE_IN_TEMPLATE.test(body)) {
    throw new Error("data contains a character that is unsafe in a template literal");
  }
  return `\`${body}\``;
}

/** Non-blank, non-comment lines of the exceptions file: one per word. */
export function countExceptions(exceptions: string): number {
  return exceptions.split(NEWLINES).filter(raw => {
    const line = raw.trim();
    return line !== "" && !line.startsWith("#");
  }).length;
}

/** The full text of src/generated/data.ts for the given source files. */
export function renderDataModule(dic: string, exceptions: string): string {
  const patterns = extractPatterns(dic);
  const exceptionLines = exceptions.split(NEWLINES);
  return [
    "// GENERATED by scripts/build-data.ts from data/hyph_is.dic and data/exceptions.txt.",
    "// Do not edit by hand. Regenerate with: bun run generate:skiptingar",
    "// hyph_is.dic is (c) Árni Magnússon Institute for Icelandic Studies, CC BY 4.0.",
    "",
    `export const PATTERNS = ${asTemplateLiteral(patterns)};`,
    "",
    `export const EXCEPTIONS = ${asTemplateLiteral(exceptionLines)};`,
    "",
    "/** Number of patterns in PATTERNS. */",
    `export const PATTERN_COUNT = ${patterns.length};`,
    "",
    "/** Number of words in EXCEPTIONS. */",
    `export const EXCEPTION_COUNT = ${countExceptions(exceptions)};`,
    "",
  ].join("\n");
}

/** Reads the source files from disk and renders the module. */
export function buildDataModule(): string {
  return renderDataModule(
    readFileSync(DIC_PATH, "utf8"),
    readFileSync(EXCEPTIONS_PATH, "utf8")
  );
}

if (import.meta.main) {
  writeFileSync(GENERATED_PATH, buildDataModule());
  console.log(`wrote ${GENERATED_PATH}`);
}
