/**
 * Compiles data/hyph_is.dic and data/exceptions.txt into src/generated/data.ts.
 *
 * Run from the repo root: bun run generate:skiptingar
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseExceptions } from "../src/parse-exceptions";
import { encodePatterns } from "../src/pattern-format";

const PACKAGE_ROOT = join(import.meta.dir, "..");

export const DIC_PATH = join(PACKAGE_ROOT, "data", "hyph_is.dic");
export const EXCEPTIONS_PATH = join(PACKAGE_ROOT, "data", "exceptions.txt");
export const GENERATED_PATH = join(PACKAGE_ROOT, "src", "generated", "data.ts");

const PATTERN_LINE = /^[\p{L}\d.]+$/u;
const UNSAFE_IN_TEMPLATE = /[`\\$]/;
const NEWLINES = /\r?\n/;

const HEADER_LINE = /^([A-Z]+) (.+)$/;

/** The hyphenation minimums that the dictionary header states. */
export type DictionaryMinimums = { leftMin: number; rightMin: number };

/**
 * Plain Liang pattern lines of a hunspell dictionary, header lines dropped,
 * sorted. The order does not matter to the engine, and sorted lines compress
 * better. The header minimums (`LEFTHYPHENMIN`, `RIGHTHYPHENMIN`) come back too.
 */
export function extractPatterns(dic: string): {
  patterns: string[];
  minimums: DictionaryMinimums;
} {
  const patterns: string[] = [];
  const header = new Map<string, string>();
  for (const raw of dic.split(NEWLINES)) {
    const line = raw.trim();
    if (line === "" || line === "UTF-8") {
      continue;
    }
    const headerLine = HEADER_LINE.exec(line);
    if (headerLine) {
      header.set(headerLine[1] ?? "", headerLine[2] ?? "");
      continue;
    }
    if (!PATTERN_LINE.test(line)) {
      throw new Error(`hyph_is.dic: unsupported pattern line: ${line}`);
    }
    patterns.push(line);
  }
  return {
    patterns: patterns.sort(),
    minimums: {
      leftMin: headerNumber(header, "LEFTHYPHENMIN"),
      rightMin: headerNumber(header, "RIGHTHYPHENMIN"),
    },
  };
}

function headerNumber(header: Map<string, string>, name: string): number {
  const value = Number(header.get(name));
  if (!Number.isInteger(value) || value < 1) {
    throw new Error(`hyph_is.dic: ${name} must be a whole number of 1 or more`);
  }
  return value;
}

function asTemplateLiteral(lines: string[]): string {
  const body = lines.join("\n");
  if (UNSAFE_IN_TEMPLATE.test(body)) {
    throw new Error("data contains a character that is unsafe in a template literal");
  }
  return `\`${body}\``;
}

/** The full text of src/generated/data.ts for the given source files. */
export function renderDataModule(dic: string, exceptions: string): string {
  const { patterns, minimums } = extractPatterns(dic);
  // Parsed only to fail the build on a malformed file and to count the words.
  const exceptionCount = parseExceptions(exceptions).size;
  const exceptionLines = exceptions.split(NEWLINES);
  return [
    "// GENERATED by scripts/build-data.ts from data/hyph_is.dic and data/exceptions.txt.",
    "// Do not edit by hand. Regenerate with: bun run generate:skiptingar",
    "",
    // A legal comment (`/*!`), so minifiers keep the credit in the shipped chunk.
    "/*! Icelandic Hyphenation Dictionary 2.0 (c) 2020 Kristján Rúnarsson, Árni Magnússon",
    " * Institute for Icelandic Studies; version 1 (1985) Baldur Jónsson and Magnús Gíslason.",
    " * CC BY 4.0, https://creativecommons.org/licenses/by/4.0/ - https://github.com/icelandic-lt/hyphenation-is */",
    // The explicit `: string` keeps the emitted declaration at one line. Left
    // to inference, it would spell out the whole literal (150 kB) in dist.
    "/** The patterns, sorted and front-coded (see src/pattern-format.ts). */",
    `export const PATTERNS: string = ${asTemplateLiteral([encodePatterns(patterns)])};`,
    "",
    `export const EXCEPTIONS: string = ${asTemplateLiteral(exceptionLines)};`,
    "",
    "/** Fewest letters before a break, from the dictionary header. */",
    `export const DATA_LEFT_MIN = ${minimums.leftMin};`,
    "",
    "/** Fewest letters after a break, from the dictionary header. */",
    `export const DATA_RIGHT_MIN = ${minimums.rightMin};`,
    "",
    "/** Number of patterns in PATTERNS. */",
    `export const PATTERN_COUNT = ${patterns.length};`,
    "",
    "/** Number of words in EXCEPTIONS. */",
    `export const EXCEPTION_COUNT = ${exceptionCount};`,
    "",
  ].join("\n");
}

/** Reads the source files from disk and renders the module. */
export function buildDataModule(): string {
  return renderDataModule(
    readFileSync(DIC_PATH, "utf8"),
    readFileSync(EXCEPTIONS_PATH, "utf8")
  );
}

if (import.meta.main) {
  writeFileSync(GENERATED_PATH, buildDataModule());
  console.log(`wrote ${GENERATED_PATH}`);
}
